/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as RezerwacjaRouteImport } from './routes/rezerwacja'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as KosmetologiaIndexRouteImport } from './routes/kosmetologia/index'
import { Route as KosmetologiaSlugRouteImport } from './routes/kosmetologia/$slug'
import { Route as OprawaOkaIndexRouteImport } from './routes/oprawa-oka/index'
import { Route as OprawaOkaSlugRouteImport } from './routes/oprawa-oka/$slug'
import { Route as TrychologiaIndexRouteImport } from './routes/trychologia/index'
import { Route as TrychologiaSlugRouteImport } from './routes/trychologia/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const RezerwacjaRoute = RezerwacjaRouteImport.update({
  id: '/rezerwacja',
  path: '/rezerwacja',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KosmetologiaIndexRoute = KosmetologiaIndexRouteImport.update({
  id: '/kosmetologia/',
  path: '/kosmetologia/',
  getParentRoute: () => rootRouteImport,
} as any)
const KosmetologiaSlugRoute = KosmetologiaSlugRouteImport.update({
  id: '/kosmetologia/$slug',
  path: '/kosmetologia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OprawaOkaIndexRoute = OprawaOkaIndexRouteImport.update({
  id: '/oprawa-oka/',
  path: '/oprawa-oka/',
  getParentRoute: () => rootRouteImport,
} as any)
const OprawaOkaSlugRoute = OprawaOkaSlugRouteImport.update({
  id: '/oprawa-oka/$slug',
  path: '/oprawa-oka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrychologiaIndexRoute = TrychologiaIndexRouteImport.update({
  id: '/trychologia/',
  path: '/trychologia/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrychologiaSlugRoute = TrychologiaSlugRouteImport.update({
  id: '/trychologia/$slug',
  path: '/trychologia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kosmetologia/$slug': typeof KosmetologiaSlugRoute
  '/oprawa-oka/$slug': typeof OprawaOkaSlugRoute
  '/trychologia/$slug': typeof TrychologiaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/kosmetologia/': typeof KosmetologiaIndexRoute
  '/oprawa-oka/': typeof OprawaOkaIndexRoute
  '/trychologia/': typeof TrychologiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kosmetologia/$slug': typeof KosmetologiaSlugRoute
  '/oprawa-oka/$slug': typeof OprawaOkaSlugRoute
  '/trychologia/$slug': typeof TrychologiaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/kosmetologia': typeof KosmetologiaIndexRoute
  '/oprawa-oka': typeof OprawaOkaIndexRoute
  '/trychologia': typeof TrychologiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kosmetologia/$slug': typeof KosmetologiaSlugRoute
  '/oprawa-oka/$slug': typeof OprawaOkaSlugRoute
  '/trychologia/$slug': typeof TrychologiaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/kosmetologia/': typeof KosmetologiaIndexRoute
  '/oprawa-oka/': typeof OprawaOkaIndexRoute
  '/trychologia/': typeof TrychologiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/rezerwacja'
    | '/blog/$slug'
    | '/kosmetologia/$slug'
    | '/oprawa-oka/$slug'
    | '/trychologia/$slug'
    | '/blog/'
    | '/kosmetologia/'
    | '/oprawa-oka/'
    | '/trychologia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/rezerwacja'
    | '/blog/$slug'
    | '/kosmetologia/$slug'
    | '/oprawa-oka/$slug'
    | '/trychologia/$slug'
    | '/blog'
    | '/kosmetologia'
    | '/oprawa-oka'
    | '/trychologia'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/rezerwacja'
    | '/blog/$slug'
    | '/kosmetologia/$slug'
    | '/oprawa-oka/$slug'
    | '/trychologia/$slug'
    | '/blog/'
    | '/kosmetologia/'
    | '/oprawa-oka/'
    | '/trychologia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  RezerwacjaRoute: typeof RezerwacjaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  KosmetologiaSlugRoute: typeof KosmetologiaSlugRoute
  OprawaOkaSlugRoute: typeof OprawaOkaSlugRoute
  TrychologiaSlugRoute: typeof TrychologiaSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  KosmetologiaIndexRoute: typeof KosmetologiaIndexRoute
  OprawaOkaIndexRoute: typeof OprawaOkaIndexRoute
  TrychologiaIndexRoute: typeof TrychologiaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezerwacja': {
      id: '/rezerwacja'
      path: '/rezerwacja'
      fullPath: '/rezerwacja'
      preLoaderRoute: typeof RezerwacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosmetologia/': {
      id: '/kosmetologia/'
      path: '/kosmetologia'
      fullPath: '/kosmetologia/'
      preLoaderRoute: typeof KosmetologiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosmetologia/$slug': {
      id: '/kosmetologia/$slug'
      path: '/kosmetologia/$slug'
      fullPath: '/kosmetologia/$slug'
      preLoaderRoute: typeof KosmetologiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oprawa-oka/': {
      id: '/oprawa-oka/'
      path: '/oprawa-oka'
      fullPath: '/oprawa-oka/'
      preLoaderRoute: typeof OprawaOkaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oprawa-oka/$slug': {
      id: '/oprawa-oka/$slug'
      path: '/oprawa-oka/$slug'
      fullPath: '/oprawa-oka/$slug'
      preLoaderRoute: typeof OprawaOkaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trychologia/': {
      id: '/trychologia/'
      path: '/trychologia'
      fullPath: '/trychologia/'
      preLoaderRoute: typeof TrychologiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trychologia/$slug': {
      id: '/trychologia/$slug'
      path: '/trychologia/$slug'
      fullPath: '/trychologia/$slug'
      preLoaderRoute: typeof TrychologiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  RezerwacjaRoute: RezerwacjaRoute,
  BlogSlugRoute: BlogSlugRoute,
  KosmetologiaSlugRoute: KosmetologiaSlugRoute,
  OprawaOkaSlugRoute: OprawaOkaSlugRoute,
  TrychologiaSlugRoute: TrychologiaSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  KosmetologiaIndexRoute: KosmetologiaIndexRoute,
  OprawaOkaIndexRoute: OprawaOkaIndexRoute,
  TrychologiaIndexRoute: TrychologiaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
